import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>music-concentration-test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to music concentration test!</h1>

        <p className={styles.description}>Get started by playing the game!</p>

        <div className={styles.grid}>
          <Link href="/play/no-music" className={styles.card}>
            <h2>Play without music &rarr;</h2>
            <p>Play the game without music in the background</p>
          </Link>

          <Link href="/play" className={styles.card}>
            <h2>Play with your music &rarr;</h2>
            <p>Play the game with your own music</p>
          </Link>

          <Link href="/stats" className={styles.card}>
            <h2>Stats &rarr;</h2>
            <p>See the stats</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
